<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing users
        DB::statement('DELETE FROM users');
        DB::statement("DELETE FROM sqlite_sequence WHERE name='users'");

        // Test User
        User::create([
            'id' => 52,
            'name' => 'Test User',
            'email' => 'test@example.com',
            'password' => Hash::make('password'),
            'role' => null,
        ]);

        // Create All Teachers
        $teachers = [
            [
                'id' => 1,
                'name' => 'Cikgu Ahmad',
                'email' => 'cikgu.ahmad@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'teacher',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60123000001',
                'user_id' => 'G-PU001-001',
            ],
            [
                'id' => 3,
                'name' => 'Ms. Julia',
                'email' => 'ms-julia@gmail.com',
                'password' => Hash::make('password'),
                'role' => 'teacher',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60123000003',
                'user_id' => 'G-PU001-003',
            ],
            [
                'id' => 53,
                'name' => 'Cikgu Ahmad',
                'email' => 'ahmad@example.com',
                'password' => Hash::make('password'),
                'role' => 'teacher',
                'district' => 'Johor Bahru',
                'school_code' => 'JB001',
                'phone' => '+60123456789',
                'user_id' => 'G-JB001-a1b',
            ],
            [
                'id' => 54,
                'name' => 'Cikgu Farah',
                'email' => 'farah@example.com',
                'password' => Hash::make('password'),
                'role' => 'teacher',
                'district' => 'Kuala Lumpur',
                'school_code' => 'KL001',
                'phone' => '+60187654321',
                'user_id' => 'G-KL001-c2d',
            ],
            [
                'id' => 55,
                'name' => 'Cikgu Ravi',
                'email' => 'ravi@example.com',
                'password' => Hash::make('password'),
                'role' => 'teacher',
                'district' => 'Selangor',
                'school_code' => 'SG001',
                'phone' => '+60134567890',
                'user_id' => 'G-SG001-e3f',
            ],
            [
                'id' => 56,
                'name' => 'Cikgu Siti',
                'email' => 'siti@example.com',
                'password' => Hash::make('password'),
                'role' => 'teacher',
                'district' => 'Penang',
                'school_code' => 'PN001',
                'phone' => '+60145678901',
                'user_id' => 'G-PN001-g4h',
            ],
            [
                'id' => 57,
                'name' => 'Cikgu Budi',
                'email' => 'budi@example.com',
                'password' => Hash::make('password'),
                'role' => 'teacher',
                'district' => 'Kedah',
                'school_code' => 'KD001',
                'phone' => '+60156789012',
                'user_id' => 'G-KD001-i5j',
            ],
        ];

        foreach ($teachers as $teacher) {
            User::create($teacher);
        }

        echo "7 Teachers created successfully.\n";

        // Create All Students
        $students = [
            [
                'id' => 5,
                'name' => 'Muhammad Amirul bin Hakim',
                'email' => 'muhammad.hakim@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000005',
                'user_id' => 'P-PU001-005',
            ],
            [
                'id' => 6,
                'name' => 'Nur Aleesya binti Fadzil',
                'email' => 'nur.fadzil@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000006',
                'user_id' => 'P-PU001-006',
            ],
            [
                'id' => 7,
                'name' => 'Tan Wei Jian',
                'email' => 'tan.jian@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000007',
                'user_id' => 'P-PU001-007',
            ],
            [
                'id' => 8,
                'name' => 'Asha a/p Manogaran',
                'email' => 'asha.manogaran@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000008',
                'user_id' => 'P-PU001-008',
            ],
            [
                'id' => 9,
                'name' => 'Muhammad Danish Rayyan bin Zulkifli',
                'email' => 'muhammad.zulkifli@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000009',
                'user_id' => 'P-PU001-009',
            ],
            [
                'id' => 10,
                'name' => 'Siti Nur Amirah binti Razlan',
                'email' => 'siti.razlan@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000010',
                'user_id' => 'P-PU001-010',
            ],
            [
                'id' => 11,
                'name' => 'Lim Jia Hui',
                'email' => 'lim.hui@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000011',
                'user_id' => 'P-PU001-011',
            ],
            [
                'id' => 12,
                'name' => 'Harith Haziq bin Rahim',
                'email' => 'harith.rahim@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000012',
                'user_id' => 'P-PU001-012',
            ],
            [
                'id' => 13,
                'name' => 'Kavinesh a/l Kumar',
                'email' => 'kavinesh.kumar@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000013',
                'user_id' => 'P-PU001-013',
            ],
            [
                'id' => 14,
                'name' => 'Chia Wen Ning',
                'email' => 'chia.ning@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000014',
                'user_id' => 'P-PU001-014',
            ],
            [
                'id' => 15,
                'name' => 'Nurul Nadhira binti Shamsul',
                'email' => 'nurul.shamsul@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000015',
                'user_id' => 'P-PU001-015',
            ],
            [
                'id' => 16,
                'name' => 'Muhammad Aiman Hakimi bin Azlan',
                'email' => 'aiman.azlan@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000016',
                'user_id' => 'P-PU001-016',
            ],
            [
                'id' => 17,
                'name' => 'Lee Zi Xuan',
                'email' => 'lee.xuan@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000017',
                'user_id' => 'P-PU001-017',
            ],
            [
                'id' => 18,
                'name' => 'Thivakar a/l Shanmugan',
                'email' => 'thivakar.shanmugan@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000018',
                'user_id' => 'P-PU001-018',
            ],
            [
                'id' => 19,
                'name' => 'Nur Syafiqah Irdina binti Fauzan',
                'email' => 'nur.fauzan@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000019',
                'user_id' => 'P-PU001-019',
            ],
            [
                'id' => 20,
                'name' => 'Muhammad Arif Danish bin Razman',
                'email' => 'arif.razman@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000020',
                'user_id' => 'P-PU001-020',
            ],
            [
                'id' => 21,
                'name' => 'Wong Yu Heng',
                'email' => 'wong.heng@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000021',
                'user_id' => 'P-PU001-021',
            ],
            [
                'id' => 22,
                'name' => 'Siti Maryam binti Khairul',
                'email' => 'siti.khairul@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000022',
                'user_id' => 'P-PU001-022',
            ],
            [
                'id' => 23,
                'name' => 'Tan Li Ying',
                'email' => 'tan.ying@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000023',
                'user_id' => 'P-PU001-023',
            ],
            [
                'id' => 24,
                'name' => 'Naufal Ikhwan bin Shafie',
                'email' => 'naufal.shafie@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000024',
                'user_id' => 'P-PU001-024',
            ],
            [
                'id' => 25,
                'name' => 'Aina Marissa binti Rahmat',
                'email' => 'aina.rahmat@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000025',
                'user_id' => 'P-PU001-025',
            ],
            [
                'id' => 26,
                'name' => 'Muhammad Hazim Firdaus bin Yusri',
                'email' => 'hazim.yusri@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000026',
                'user_id' => 'P-PU001-026',
            ],
            [
                'id' => 27,
                'name' => 'Lim Wei Xuan',
                'email' => 'lim.xuan@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000027',
                'user_id' => 'P-PU001-027',
            ],
            [
                'id' => 28,
                'name' => 'Sharveen a/l Prakash',
                'email' => 'sharveen.prakash@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000028',
                'user_id' => 'P-PU001-028',
            ],
            [
                'id' => 29,
                'name' => 'Nur Syazwina binti Salleh',
                'email' => 'syazwina.salleh@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000029',
                'user_id' => 'P-PU001-029',
            ],
            [
                'id' => 30,
                'name' => 'Muhammad Irfan Danish bin Azmi',
                'email' => 'irfan.azmi@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000030',
                'user_id' => 'P-PU001-030',
            ],
            [
                'id' => 31,
                'name' => 'Chan Jing Wen',
                'email' => 'chan.wen@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000031',
                'user_id' => 'P-PU001-031',
            ],
            [
                'id' => 32,
                'name' => 'Siti Balqis binti Azhar',
                'email' => 'siti.azhar@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000032',
                'user_id' => 'P-PU001-032',
            ],
            [
                'id' => 33,
                'name' => 'Ganes a/l Devan',
                'email' => 'ganes.devan@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000033',
                'user_id' => 'P-PU001-033',
            ],
            [
                'id' => 34,
                'name' => 'Ho Zi Jie',
                'email' => 'ho.jie@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000034',
                'user_id' => 'P-PU001-034',
            ],
            [
                'id' => 35,
                'name' => 'Nur Fatin Amani binti Kamarul',
                'email' => 'fatin.kamarul@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000035',
                'user_id' => 'P-PU001-035',
            ],
            [
                'id' => 36,
                'name' => 'Muhammad Aqil Zafran bin Razak',
                'email' => 'aqil.razak@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000036',
                'user_id' => 'P-PU001-036',
            ],
            [
                'id' => 37,
                'name' => 'Wong Jia Le',
                'email' => 'wong.jiale@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000037',
                'user_id' => 'P-PU001-037',
            ],
            [
                'id' => 38,
                'name' => 'Navinya a/p Murugan',
                'email' => 'navinya.murugan@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000038',
                'user_id' => 'P-PU001-038',
            ],
            [
                'id' => 39,
                'name' => 'Nur Adlina Sofea binti Halim',
                'email' => 'adlina.halim@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000039',
                'user_id' => 'P-PU001-039',
            ],
            [
                'id' => 40,
                'name' => 'Muhammad Harraz Haziq bin Naim',
                'email' => 'harraz.naim@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000040',
                'user_id' => 'P-PU001-040',
            ],
            [
                'id' => 41,
                'name' => 'Tan Kai Ren',
                'email' => 'tan.kairen@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000041',
                'user_id' => 'P-PU001-041',
            ],
            [
                'id' => 42,
                'name' => 'Siti Husna binti Yasin',
                'email' => 'siti.yasin@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000042',
                'user_id' => 'P-PU001-042',
            ],
            [
                'id' => 43,
                'name' => 'Teo Jun Hao',
                'email' => 'teo.hao@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000043',
                'user_id' => 'P-PU001-043',
            ],
            [
                'id' => 44,
                'name' => 'Aisyah Irdina binti Fauzi',
                'email' => 'aisyah.fauzi@smkpu.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Putrajaya',
                'school_code' => 'PU001',
                'phone' => '+60210000044',
                'user_id' => 'P-PU001-044',
            ],
            [
                'id' => 58,
                'name' => 'Muhammad Ali',
                'email' => 'ali@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Johor Bahru',
                'school_code' => 'JB001',
                'phone' => '+60211111111',
                'user_id' => 'P-JB001-k6l',
            ],
            [
                'id' => 59,
                'name' => 'Nur Aisha',
                'email' => 'aisha@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Kuala Lumpur',
                'school_code' => 'KL001',
                'phone' => '+60212222222',
                'user_id' => 'P-KL001-m7n',
            ],
            [
                'id' => 60,
                'name' => 'Rajesh Kumar',
                'email' => 'rajesh@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Selangor',
                'school_code' => 'SG001',
                'phone' => '+60213333333',
                'user_id' => 'P-SG001-o8p',
            ],
            [
                'id' => 61,
                'name' => 'Ying Ying Chen',
                'email' => 'yingying@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Penang',
                'school_code' => 'PN001',
                'phone' => '+60214444444',
                'user_id' => 'P-PN001-q9r',
            ],
            [
                'id' => 62,
                'name' => 'Zain Zahari',
                'email' => 'zain@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'district' => 'Kedah',
                'school_code' => 'KD001',
                'phone' => '+60215555555',
                'user_id' => 'P-KD001-s0t',
            ],
        ];

        foreach ($students as $student) {
            User::create($student);
        }

        echo "45 Students created successfully.\n";
        echo "Total: 53 users (1 test user, 7 teachers, 45 students).\n";
    }
}
